### ISSUE TITLE
[Improve]: melos 側のバージョン管理を充実

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#109]
![next-badge](https://img.shields.io/badge/review-next-blueviolet)

各パッケージで同じライブラリを利用しているケースが多くなってきたので, そろそろ melos 側のバージョン管理を充実させて良いかも？と思いました 💡
ただ、今回の PR の本筋ではないので別 PR で良いのかなと思っています。

https://github.com/yumemi-inc/flutter-mobile-project-template/blob/425ab7abac9539912126eeb022e391b5c248fcd4/melos.yaml#L10-L16

_Originally posted by @tatsutakein in https://github.com/yumemi-inc/flutter-mobile-project-template/pull/102#discussion_r1473752988_

**Comment by tatsutakein** [comment]
こちら、自分が言い出しっぺなので対応しようと思います〜！
