### ISSUE TITLE
[Feature]: テンプレート機能使用時に必要な初期設定をIssueでリストアップする

### ISSUE THREAD

**Issue by Yamasaki-pan961** [yumemi-inc/flutter-mobile-project-template#114]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 動機

テンプレート機能使用時に必要な初期設定をわかりやすく伝えたい。

### 提案

テンプレート機能使用時に必要な初期設定をIssueでリストアップするワークフローを作成する

**Comment by blendthink** [comment]
作成する Issue
- レビュアーの設定（適切なトークン設定も含めて)。ただし、人数が少ない場合はチームではなく `hkusu/review-assign-action` を利用しても良い
