### ISSUE TITLE
[Feature]: Settingページからライセンスやアプリバージョンを表示できるようにする

### ISSUE THREAD

**Issue by Yamasaki-pan961** [yumemi-inc/flutter-mobile-project-template#116]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 動機

ライセンスやアプリバージョンの確認が現状できない。

### 提案

Settingページからライセンスやアプリバージョンを表示できるようにする

**Comment by tatsutakein** [comment]
こちらやりたいのでセルフアサインします〜！
