### ISSUE TITLE
[Bug]: WebViewをスワイプしてもアプリに戻れない

### ISSUE THREAD

**Issue by Yamasaki-pan961** [yumemi-inc/flutter-mobile-project-template#119]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 現在の動作

WebViewを左からスワイプしてもアプリに戻れない。　

### 期待される動作

WebViewを左からスワイプすることでアプリに戻れる。

WillPopScope 周辺のマイグレーションガイド 
https://yumemi.slack.com/archives/C0585H2BG9L/p1707119105411589?thread_ts=1707116364.259649&cid=C0585H2BG9L

### 環境

```Markdown
- Commit Hash: 4d36ce883de3ba8612676e8d5259f9977724ed38
```

**Comment by iseruuuuu** [comment]
# メモ

iOSにてcanPopをfalseにするとback gestureがうまく動かないっぽいです

https://github.com/flutter/flutter/issues/138624
