### ISSUE TITLE
アプリアイコン自動生成

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#12]
- 環境によってアイコン分ける

FYI:
- https://zenn.dev/altiveinc/articles/separating-environments-in-flutter#%E3%82%A2%E3%83%97%E3%83%AAicon%E3%82%92%E7%92%B0%E5%A2%83%E5%88%A5%E3%81%AB%E5%88%86%E3%81%91%E3%82%8B%E5%A0%B4%E5%90%88%E3%81%AB%E5%BF%85%E8%A6%81%E3%81%AA%E3%81%93%E3%81%A8
- https://pub.dev/packages/flutter_launcher_icons

**Comment by iseruuuuu** [comment]
Q、アイコンの作成の場所について
・app/appsの中で作成する？
・
Q、アイコンの画像はどうするのか？
・現状だとアイコンを生成せずに必要な記載のみを行う？
・

**Comment by iseruuuuu** [comment]
# Androidについて
Android8以上は[アダプティブアイコン](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive?hl=ja)といって、デバイスモデルごとに異なるアイコンの図形を表示できますので、背景透過し約50%縮小した画像も用意する必要がありそうです。

アダプティブアイコンに対応しないこともできますが、Android端末でアイコンが見切れてしまうので対応は必須と思います。

**Comment by iseruuuuu** [comment]
# やること

- アイコンの生成を行う(dev prd, stg)
- アイコンの生成に必要な画像を用意する
- docsにアイコンについての仕様を記載する
