### ISSUE TITLE
[Improve]: GitHub Actions のワークフローで適切な melos のバージョンを使うようにする

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#147]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 背景

現在、GitHub Actions のワークフローでバージョンを指定していないため、最新バージョンを利用するようになっている

### 提案の詳細

実際にプロジェクトで使用しているバージョンを使用できるように↓のようにする。

```shell
dart pub get
dart run melos bootstrap
```

### 環境

```Markdown
- Commit Hash: b709dc4ebfc76203fdce4abcd75140b646155f74
```

**Comment by YumNumm** [comment]
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
このPR元から切る
https://github.com/yumemi-inc/flutter-mobile-project-template/pull/156
