### ISSUE TITLE
[Feature]: ページング機能のエラー発生時の復帰処理を実装する

### ISSUE THREAD

**Issue by trm11tkr** [yumemi-inc/flutter-mobile-project-template#173]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 動機

#2 にて基礎的なページング機能は実装しますが、2ページ目以降にエラーが発生した場合の復帰処理は未実装です。

### 提案

2ページ目以降にエラーが発生した場合の復帰処理を実装する。

参考: #2 では 以下の記事を参考に実装予定です。
https://zenn.dev/k9i/articles/b8c333e1bb8b9b

**Comment by Aosanori** [comment]
僭越ながら取り組ませていただきます！

**Comment by Aosanori** [comment]
@blendthink 
YouTubeアプリ等を参考にし、オンラインに復帰したら自動的に読み込みを再開するような動作を実現するために、
以下のような`connectivity_plus`パッケージを利用してオンラインかどうかを状態に持つようなProviderを作成してみました。

しかしながら`connectivity_plus`パッケージはiOSシミュレータのみにおいて接続状況を正常に取得できない問題があります。
現在、issueはcloseされていますが最近でもいくらかまだ同じ問題が発生していることが報告されているようです。
私の環境では手元のMacのWifiを切り替えでは接続状況を取得できたり出来なかったりと動作が不安定でした。

https://github.com/fluttercommunity/plus_plugins/issues/479

```dart
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'connectivity_status_provider.g.dart';

@Riverpod(keepAlive: true)
class ConnectivityStatus extends _$ConnectivityStatus {
  @override
  Stream<bool> build() async* {
    connectivityStatus();
  }

  void connectivityStatus() {
    Connectivity().onConnectivityChanged.listen((connectivityResult) {
      state = AsyncData(_isOnline(connectivityResult));
    });
  }

  bool _isOnline(List<ConnectivityResult> connectivityResult) {
    const networkSource = [
      ConnectivityResult.mobile,
      ConnectivityResult.wifi,
      ConnectivityResult.ethernet,
    ];
    final result =
        connectivityResult.map(networkSource.contains).toList().contains(true);
    return result;
  }
}
```
動作例

https://github.com/yumemi-inc/flutter-mobile-project-template/assets/60128781/2e05a2f3-81ce-42f2-ac31-0e8999eb84d8

**Comment by blendthink** [comment]
@Aosanori 
実装方針のご検討ありがとうございます！

本来であればオフラインかどうかの判定も重要なのですが、いったんオフライン独自の実装は除外して検討していただけると助かります 🙏 
というのも、次の理由からです。
- オフラインかどうか監視しないアプリがある
- オフライン時の UI/UX は異なる場合が多い（イメージ）

今回は、エラー発生時の復帰処理の実装ですので、オフラインかどうかはあまり気にせず、 API 実行時にエラーが発生したさいにどのように復帰させるかをご検討いただけると助かります！
現在のように SnackBar を表示する形だと、一部のレイアウトが隠れてしまったり、一定時間で消えてしまったりするので、例えば一番下に再実行ボタンを表示させるなどの対応が良さそうな気がしているのですが、想像できますでしょうか？

**Comment by Aosanori** [comment]
@blendthink 
このようなイメージで間違いないでしょうか？
<img width="602" alt="image" src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/60128781/c772717a-5242-46af-8078-50a7b4abd9f9">

**Comment by blendthink** [comment]
@Aosanori 
まさにそのようなイメージです！
ありがとうございます！

**Comment by Aosanori** [comment]
承知いたしました！
この方針で実装していきます！

**Comment by Aosanori** [comment]
@blendthink 
以下のような動作にしてみましたがいかがでしょうか？

https://github.com/yumemi-inc/flutter-mobile-project-template/assets/60128781/9cdbf0fe-6aaf-4501-b64c-1a5896bdf85e

**Comment by blendthink** [comment]
@Aosanori 
動作については LGTM です！ありがとうございます！
アイコンや文言はエラーによって切り替えればいいかなと思いますが、いったん固定でも大丈夫です 🙆‍♂️

**Comment by Aosanori** [comment]
承知いたしました！お忙しい中ご確認ありがとうございます！
これについてPRを提出すればよろしいですか？

**Comment by blendthink** [comment]
はい、その認識であっています 🙆‍♂️

**Comment by Aosanori** [comment]
承知いたしました！お忙しい中ありがとうございます！
