### ISSUE TITLE
[Improve]: apps/app パッケージに存在する feature/home のディレクトリ構成を修正する

### ISSUE THREAD

**Issue by Kotaro666-dev** [yumemi-inc/flutter-mobile-project-template#180]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 背景

- feature/home に存在する UI 画面 HomePage のみ別パッケージに切り出せていない状態で残っている

### 提案の詳細

~~他の画面のように、packages/features に新しいパッケージとして切り出す~~

```
 features git:(main) ✗ tree -L 1
.
├── debug_mode
├── github_repository
├── setting
└── webview
```

home_page.dart はディレクトリ構成を以下のように修正する

- Before: app/lib/feature/home/ui/home_page.dart
- After: app/lib/ui/home_page.dart

### 環境

```Markdown
- Commit Hash: fb34516355ade8ef6ead69156a921cf177bc860c
```

**Comment by blendthink** [comment]
@Kotaro666-dev 
home_page.dart は packages/features/github_repository を参照しているため、packages/features に新しいパッケージとして切り出すと、 packages/features から packages/features を参照することになってしまい、アーキテクチャとしての複雑度が高まってしまい、パッケージ切り出しによるメリットが低下してしまいそうです。

いったん home_page.dart はディレクトリ構成を少し修正するだけにするか、 packages/features/home として切り出して、そこに packages/features/github_repository を統合するというのはありかなと思いましたが、いかがでしょうか？

**Comment by Kotaro666-dev** [comment]
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

> home_page.dart は packages/features/github_repository を参照しているため、packages/features に新しいパッケージとして切り出すと、 packages/features から packages/features を参照することになってしまい、アーキテクチャとしての複雑度が高まってしまい、パッケージ切り出しによるメリットが低下してしまいそうです。

上記のコメント内容を確認した。
home_page.dart クラスは packages/features/github_repository を参照している。

```dart
class HomePage extends ConsumerWidget {
  const HomePage({
    super.key,
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final l = L10n.of(context);
    final navigator = ref.watch(homeNavigatorProvider);
    return Scaffold(
      // 省略
      body: const GitHubRepositoryList(),
    );
  }
}
```

**Comment by Kotaro666-dev** [comment]
@blendthink 

フィードバックありがとうございます。
本 issue 作成時には home_page.dart の依存関係をしっかりと確認できていませんでいた！

> いったん home_page.dart はディレクトリ構成を少し修正するだけにするか、 packages/features/home として切り出して、そこに packages/features/github_repository を統合するというのはありかなと思いましたが、いかがでしょうか？

本 issue で取り上げている内容は優先度的に高いものではないため、「home_page.dart はディレクトリ構成を少し修正するだけにする」方針で対応します。
