### ISSUE TITLE
[Bug]: GitHub ActionsのCIに時間がかかる

### ISSUE THREAD

**Issue by Yamasaki-pan961** [yumemi-inc/flutter-mobile-project-template#191]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 現在の動作

Templateとして作成したリポジトリで、
GitHub ActionsのCIに時間がかかりデフォルトの制限時間10分を超えるため、CIが失敗する。

### 期待される動作

なるべく短くなるように改善する。
どう改善するかは未定。
以下が対応されると改善されるかも。
- #19 

### 環境

```Markdown
- Commit Hash: c761fb804492a901765d33330d23da16f0cde50f
```

**Comment by blendthink** [comment]
こちらキャッシュがないとき失敗してしまうと思うので、何かしら改善しないとですね。。
（どこが時間かかっているのだろう、、）

ひとまずは 15 分とかにするとか、時間を少し伸ばすとかですね。

**Comment by blendthink** [comment]
時間のかかっているステップ
- Report custom_lint result
- Check format

該当のステップは、並列処理も行っているはず。

おそらく analyzer の処理の問題もあるので、時間がかかってしまうのは現状仕方ないかもしれない。

**Comment by Yamasaki-pan961** [comment]
ジョブを並列にした結果、12分ぐらいで完了します。
Formatがかなり時間かかっていますね
https://github.com/yumemi/nap-camp-mock/actions/runs/8979954766?pr=49
