### ISSUE TITLE
[Feature]: `package/features`以下にパッケージを作成するmason brickを追加する

### ISSUE THREAD

**Issue by Yamasaki-pan961** [yumemi-inc/flutter-mobile-project-template#202]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 動機

現状は`package/cores`以下にパッケージを作るbrickしかなく、featureを追加する手間を省略したい

### 提案

 `package/features`以下にパッケージを作成するmason brickを追加する

**Comment by morikann** [comment]
合わせて mason の hooks で dart, flutter バージョンの自動更新、yumemi_lints の利用する lint バージョンの自動更新もした方が良さそう📝

**Comment by tatsutakein** [comment]
やります〜 🙋
