### ISSUE TITLE
[Feature]: ルートにあるmelos.yamlやpubspec.yamlの`name`プロパティを変更するワークフローを作成する

### ISSUE THREAD

**Issue by Yamasaki-pan961** [yumemi-inc/flutter-mobile-project-template#203]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 動機

テンプレート使用先でmelos.yamlやpubspec.yamlの`name`が`template`や`template_workspace`のままである。

### 提案

`name`プロパティをテンプレート使用先のリポジトリ名に変更するワークフローを作成する

**Comment by daichikuwa0618** [comment]
- https://github.com/yumemi-inc/flutter-mobile-project-template/blob/386508e890e983574e2487b9fdad98e78b79f76c/.github/initialization/RENAME_APPLICATION_ID.md が参考になるかも。
  - 別 Issue を作ってもいいし、「プレースホルダーを適切なものに設定する」みたいな Issue に昇華して、そこにまとめても良さそう
- また、 `flutter_app` という package 名も若干プレースホルダーのような印象を受けるので、合わせて対応してもいいかも
  - https://github.com/yumemi-inc/flutter-mobile-project-template/blob/386508e890e983574e2487b9fdad98e78b79f76c/apps/app/lib/router/provider/router.dart#L10-L13
  - Issue 範囲が大きくなりそうだったら分けるで良し。

**Comment by blendthink** [comment]
いったんはコスパを考え、Issue を作成するくらいで良さそう
