### ISSUE TITLE
[Improve]: docsにあるドキュメントを日本語化する

### ISSUE THREAD

**Issue by K9i-0** [yumemi-inc/flutter-mobile-project-template#211]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 背景

docsディレクトリにテンプレートプロジェクトに関するドキュメントがあるが、英語と日本語が混在している

### 提案の詳細

以下のようにする
日本語ドキュメント: そのまま
英語ドキュメント: GET_STARTED-EN.md等にリネーム、日本語版を-ENなしで作成し相互にリンク

dioのReadmeが参考になる
https://github.com/cfug/dio/tree/main/dio

### 環境

```Markdown
- Commit Hash: 0153501e8487f388e99243d36f56509ea98f9def
- App Version: 1.0.0
- Platform: iOS 17.2.1, Android 14 API level 34
```

**Comment by mqkotoo** [comment]
[memo]
https://yumemi.slack.com/archives/C0585H2BG9L/p1717058611318479?thread_ts=1717051808.255159&cid=C0585H2BG9L

**Comment by mqkotoo** [comment]
[memo]
https://yumemi.slack.com/archives/C0585H2BG9L/p1717058611318479?
thread_ts=1717051808.255159&cid=C0585H2BG9L
