### ISSUE TITLE
デザインシステムのパッケージ化

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#22]
- cores/designsystem に作成
- 様々な Theme の設定についてある程度網羅

FYI:
- https://docs.flutter.dev/cookbook/design/themes
- https://itome.team/blog/2019/12/flutter-advent-calendar-day12/

## 対応しないこと

- ダークモード設定の保存
- [ThemeExtension](https://api.flutter.dev/flutter/material/ThemeExtension-class.html)

**Comment by tatsutakein** [comment]
📝 packages/cores/designsystem に作成する
