### ISSUE TITLE
メンテナンスモード・強制バージョンアップ

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#24]

**Comment by iseruuuuu** [comment]
もしかしたら僕の理解が間違っているかもしれませんが、強制バージョンアップ（強制アップデート）についての使えそうなPackageなどを載せておきます🙇

- new_version
  -  Published 10 months age
  - 584 LIKE
  - 110 PUB POINTS
  - 97 POPULARITY

https://pub.dev/packages/new_version

- upgrader

**Comment by Kotaro666-dev** [comment]
# メンテナンスモードの設計

## 表示パターン

- ネイティブ画面（ダイアログ含む）
- WebView 画面

## サーバからの必要情報

- （必須）メンテナンスモード中かどうかのフラグ
- （任意）画面に表示する文言（例: メンテナンス期間）

**Comment by Kotaro666-dev** [comment]
# 強制バージョンアップ

## 表示パターン

- ネイティブ画面（ダイアログ含む）

## サーバからの必要情報

- （必須）強制バージョンアップのターゲットとなる iOS/Android バージョン番号（String）
- （任意）任意バージョンアップのターゲットとなるバージョン番号（String）

**Comment by Kotaro666-dev** [comment]
# クラス設計

## AppStatus

メンテナンスモードや強制バージョンアップのアプリ状態を保持する役割を持つ。
AppStatusProvider クラス内ではメンテナンスモードと強制バージョンアップの状態を watch する。
アプリが存続する限りメモリ上に保持したいため、自動で dispose されないようにしたほうがよさそう。  

- AppStatus class
- AppStatusProvider class

## MaintenanceModeStatus

- MaintenanceModeStatus class
- MaintenanceModeStatusProvider class

## ForceUpdateVersion

強制バージョンアップのターゲットとなる iOS/Android バージョン番号（String）を管理する。
内部で `forceUpdateEnabled` メソッドをはやし、強制バージョンアップなのかどうかを OS 別に判定する。

- ForceUpdateVersion class
- ForceUpdateVersionProvider class

## AppLifecycleState

アプリ内の状態を管理する

- AppLifecycleStateObserver
- AppLifecycleStateProvider

**Comment by Kotaro666-dev** [comment]
# アプリがバックグラウンドからフォアグラウンド復帰したことを検知する

```dart
import 'package:flutter_hooks/flutter_hooks.dart';

final appLifecycleState = useAppLifecycleState();

useEffect(
  () {
    if (appLifecycleState == AppLifecycleState.resumed) {
      /// Example: Update maintenance mode status and force update status
      debugPrint('resumed');
    }
    return null;
  },
  [appLifecycleState],
);
```

**Comment by Kotaro666-dev** [comment]
# listen したアプリ状態に応じて、メンテナンスモード・強制バージョンアップへの対応をする場合の例

```dart
ref.listen(appStatusProvider, (previous, next) {
  final isMaintenanceModeEnabled =
      previous?.maintenanceModeStatus.enabled == false &&
          next.maintenanceModeStatus.enabled;
  final isMaintenanceModeDisabled =
      (previous?.maintenanceModeStatus.enabled ?? false) &&
          !next.maintenanceModeStatus.enabled;
  final isForceUpdateStatusEnabled =
      previous?.forceUpdateStatus.enabled == false &&
          next.forceUpdateStatus.enabled;

  if (isMaintenanceModeEnabled) {
    /// Example: Display maintenance mode screen
    debugPrint('Maintenance mode is enabled');
  } else if (isMaintenanceModeDisabled) {
    /// Example: Close maintenance mode screen
    debugPrint('Maintenance mode is disabled');
  } else if (isForceUpdateStatusEnabled) {
    /// Example: Request forced update action to the user
    debugPrint('Force update is enabled');
  }
});
```

**Comment by Kotaro666-dev** [comment]
# メモ

アプリ内の遷移に関しては、`go_router` パッケージを使う方針という認識。

対応 issue : Navigation に go_router を使用する #51

**Comment by Kotaro666-dev** [comment]
# go_router でダイアログを表示する

参考資料を見る感じ、`Page` を継承したクラスを使ってダイアログ表示を実装できそう。

## 参考資料

- [[How Do I Show a Dialog in Flutter Using a go_router Route?](https://stackoverflow.com/questions/75690299/how-do-i-show-a-dialog-in-flutter-using-a-go-router-route)](https://stackoverflow.com/questions/75690299/how-do-i-show-a-dialog-in-flutter-using-a-go-router-route)
- [Adding Modal Routes to your GoRouter](https://croxx5f.hashnode.dev/adding-modal-routes-to-your-gorouter)

**Comment by Kotaro666-dev** [comment]
# Flutter 3.13 から追加された AppLifecycleListner

参考資料: https://api.flutter.dev/flutter/widgets/AppLifecycleListener-class.html

**Comment by Kotaro666-dev** [comment]
## 残タスク

- `go_router` パッケージの `redirect` 機能を使用して、メンテナンスモードと強制バージョンアップの画面表示基盤を用意する
- provider のふるまいを制御した形式で、両機能の画面が表示される（routeが移動するかの確認）かの単体テストを含める

**Comment by Kotaro666-dev** [comment]
# `redirect` の実装コード

https://github.com/flutter/packages/blob/855e283fa8cc3e33389244b2f883e8d2b2cebea9/packages/go_router/lib/src/configuration.dart#L350-L431

**Comment by Kotaro666-dev** [comment]
## go_router_builder で自動生成した際に appRoutes が重複する

https://github.com/flutter/flutter/issues/122258
