### ISSUE TITLE
[Improve]: featureパッケージ追加後に画面が開けるまでの手順のdocが欲しい

### ISSUE THREAD

**Issue by K9i-0** [yumemi-inc/flutter-mobile-project-template#251]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 背景

結構複雑なので
```
appのpubspecに依存を追加
melos bs
navigatorパッケージの遷移元機能のNavigatorにメソッドの宣言を追加
appのNavigatorの実装にgoメソッドの実装を追加
appに新画面のRouteを追加
appにTypedGoRouteを追加
navigatorとappのコード生成
appで追加パッケージのl10nをMaterialAppに追加
画面の呼び出しもとを実装
```
https://yumemi.slack.com/archives/C0585H2BG9L/p1718176567346549?thread_ts=1718109101.023699&cid=C0585H2BG9L

### 環境

```Markdown
- Commit Hash: 0153501e8487f388e99243d36f56509ea98f9def
- App Version: 1.0.0
- Platform: iOS 17.2.1, Android 14 API level 34
```

**Comment by mqkotoo** [comment]
@Aosanori 
以下のissueをこのissueで合わせて対応するでいいよね？
https://github.com/yumemi-inc/flutter-mobile-project-template/issues/253

**Comment by mqkotoo** [comment]
https://github.com/yumemi-inc/flutter-mobile-project-template/issues/271
これできそうだったら、l10nのセクションは省略できるかもだからちょっと考えてみるか

**Comment by Aosanori** [comment]
@mqkotoo 
> 以下のissueをこのissueで合わせて対応するでいいよね？
いいと思う！
