### ISSUE TITLE
[Improve]: Android / iOS で Application ID / Bundle ID を別々に設定できるようにしてはどうか

### ISSUE THREAD

**Issue by daichikuwa0618** [yumemi-inc/flutter-mobile-project-template#257]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 背景

現状の https://github.com/yumemi-inc/flutter-mobile-project-template/blob/e5fdf52c21c72d4928de32204489a19acd8a6aa8/tools/rename-application-id.sh は Android / iOS 共通のアプリ ID を設定するものになっている。

### 提案の詳細

Android / iOS 別で設定できるようにする。具体的には、各 flavor の `appId` を 2 つ用意して、各 OS のプロジェクトからは別々に参照させる形。

実現方法としては、

1. https://github.com/yumemi-inc/flutter-mobile-project-template/blob/e5fdf52c21c72d4928de32204489a19acd8a6aa8/tools/rename-application-id.sh に引数を追加して 2 つの引数を要求する
   - この場合、順番が分かりにくくなりそう
2. 設定を別ファイルに定義しておき、それを読み込ませる形にする
   - `configuration.yaml` 的なファイルを用意して、そこに定義
   - #203 の設定値もここに書けるようになる

辺りが思いつき、今後の拡張性や利用者からみた簡便さから後者が望ましいと考える。

### 環境

```Markdown
- Commit Hash: 0153501e8487f388e99243d36f56509ea98f9def
- App Version: 1.0.0
- Platform: iOS 17.2.1, Android 14 API level 34
```

**Comment by K9i-0** [comment]
1が楽そうなので良いかなーと思いました
>この場合、順番が分かりにくくなりそう

ミスってもコミットしなければいいだけだしそんな気にならなさそう

**Comment by daichikuwa0618** [comment]
📝 https://github.com/yumemi-inc/flutter-mobile-project-template/blob/e5fdf52c21c72d4928de32204489a19acd8a6aa8/.github/initialization/RENAME_APPLICATION_ID.md の追従が必要。

**Comment by daichikuwa0618** [comment]
かなり #203 を意識していたので、無駄な先回りだったかもですね 😓 
1 案ならサクッとできそうですし、自分のほうで対応します。
