### ISSUE TITLE
WebView 画面

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#26]

**Comment by iseruuuuu** [comment]
# 自分なりの考え
- webViewについては、[flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview)を使用した方が良さそう。

**Comment by iseruuuuu** [comment]
# 作業予定の内容
- WebViewの表示
- iOS の横スワイプと Android の戻るボタンで１つ前のページがあれば WebView 内でそのページに戻る
- WebView が初回ページロード中のときに、ローディングを表示
- WebView でエラー発生したらエラー画面を表示
- pull-to-refresh

## 注意事項
- 作業量によってPRを分ける場合あり。
- WebViewには、[webview_flutter](https://pub.dev/packages/webview_flutter)というflutter.dev公式のパッケージがあるが、 flutter_inappwebview のほうが使い勝手が良さそうだと考え、現時点（2024/01/26）では、[flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview)を使用して開発する予定。

**Comment by iseruuuuu** [comment]
### メモ
```
iOS の横スワイプと Android の戻るボタンで１つ前のページがあれば WebView 内でそのページに戻る
```
- WillPopScopeを使用して、`await controller.canGoBack()`でひとつ前のページがあれば戻るように実装してみる

https://inappwebview.dev/blog/convert-a-pwa-into-a-flutter-app-using-webviews/#willpopscope

**Comment by iseruuuuu** [comment]
# メモ
```
pull-to-refresh
```

この辺りの実装できそう

```
  @override
  void initState() {
    super.initState();
    _pullToRefreshController = PullToRefreshController(
      settings: PullToRefreshSettings(color: Colors.blue),
      onRefresh: () async {
        if (Platform.isAndroid) {
          await _webViewController?.reload();
        } else if (Platform.isIOS) {
          await _webViewController?.loadUrl(
            urlRequest: URLRequest(
              url: await _webViewController?.getUrl(),
            ),
          );
        }
      },
    );
  }

  pullToRefreshController: _pullToRefreshController,
              onLoadStop: (_, __) async {
                await _pullToRefreshController?.endRefreshing();
  },
```

**Comment by iseruuuuu** [comment]
# メモ

```
WebView が初回ページロード中のときに、ローディングを表示
```

これで実装できそう

```
 final isLoading = useState(false);

              onLoadStart: (_, __) {
                isLoading.value = true;
              },
              onLoadStop: (_, __) async {
                await _pullToRefreshController?.endRefreshing();
                isLoading.value = false;
              },
              onReceivedError: (controller, request, error) async {
                await _pullToRefreshController?.endRefreshing();
                isLoading.value = false;
              },
            ),
```

**Comment by iseruuuuu** [comment]
# まだできていない実装について(2024/02/02現在)
- WebView でエラー発生したらエラー画面を表示
 Androidで1ページ→2ページの遷移でエラー画面が出る実装
 エラー画面のリフレッシュ機能の実装

**Comment by iseruuuuu** [comment]
## 残りのタスク
- WebView でエラー発生したらエラー画面を表示
- エラー画面のリフレッシュ機能の実装
- WebViewのパフォーマンス改善
