### ISSUE TITLE
[Improve]: デバッグ系画面を開発時のみ利用可能にする

### ISSUE THREAD

**Issue by K9i-0** [yumemi-inc/flutter-mobile-project-template#267]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 背景

#235 から分離

### 環境

```Markdown
- Commit Hash: 0153501e8487f388e99243d36f56509ea98f9def
- App Version: 1.0.0
- Platform: iOS 17.2.1, Android 14 API level 34
```

**Comment by mqkotoo** [comment]
[memo]
単純にkDebugModeで表示非表示するのか、おかやまんさんがおっしゃっていたようなどこかのボタン押すと遷移するみたいにするかどっちがいいのか

**Comment by blendthink** [comment]
FYI:
https://github.com/FlutterKaigi/2024/blob/2b3645d407c54c0b8f68490239d2f302e04e128e/apps/app/lib/routing/router.dart#L27

**Comment by tatsutakein** [comment]
割り当て済みだった Issue の PR が作成できたため、こちらに着手いたします 🙋
