### ISSUE TITLE
[Feature]: ナビゲーションデバッグ画面で引数がある場合などに対応する

### ISSUE THREAD

**Issue by K9i-0** [yumemi-inc/flutter-mobile-project-template#268]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 動機

#266 でナビゲーションデバッグ画面を実装したが、パラメーターがあると遷移できない

### 提案

TextFieldとかで入力させる？

**Comment by blendthink** [comment]
複雑なデータクラスを渡す画面は、手入力するのは現実的ではない。
そのため、仮のデータを用意できるようにして遷移可能にする。

**Comment by blendthink** [comment]
macro とか使う場合には、 Flutter のバージョンを仮で更新する必要がありそう。

**Comment by mj-hd** [comment]
macrosですが、Analyzerの挙動がなかなか不安定で時間が溶けてしまいそうでした...。extraの対応などは捨て、手入力でパラメータを指定できるようなもっと素直な方針に切り替えたいと思います

**Comment by blendthink** [comment]
📝 
- パスパラメータはパスから取得可能
- カスタムパラメータ・クエリパラメータは XxxRoute クラスを確認するしかない
- まだまだ macros の挙動が安定していないため、ひとまず手入力できる形にする

**Comment by blendthink** [comment]
#293 で対応しきれなかった部分を別 Issue として切り出しました。
#296 

よって、こちらの Issue はクローズさせていただきます！
