### ISSUE TITLE
[Improve] 初期に自動的に登録される Issue を整理

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#274]
## 概要

一部の docs 配下のものも移動する
- https://github.com/yumemi-inc/flutter-mobile-project-template/blob/main/docs/ja/ABOUT_ICON.md
- https://github.com/yumemi-inc/flutter-mobile-project-template/blob/main/docs/ja/FIREBASE_HOSTING_PREVIEW.md
  - ただし、現状あるものと統合する
    - https://github.com/yumemi-inc/flutter-mobile-project-template/blob/main/.github/initialization/DEPLOYMENT_WITHIN_PR.md
  - 画像については一度アップロードして、その URL を使い回す
  - Firebase Hosting はデフォルトで一般公開されてしまうため、注意書きを書きたいが、別PRで行う
- https://github.com/yumemi-inc/flutter-mobile-project-template/blob/main/docs/ja/SPLASH_SCREEN.md

**Comment by tatsutakein** [comment]
📝 
現在 docs で記載されているものを Issue 化する。
ja / en で追加しつつ、ja で作成するよう仕組み化する。

**Comment by tatsutakein** [comment]
やります 🙋

**Comment by tatsutakein** [comment]
📝 memo

- どういう方針でアーキテクチャを採用するかの議論用 Issue もあると良さそう
