### ISSUE TITLE
[Improve]: grind についてのドキュメントを追加

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#279]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 背景

以下のプルリクエストで grinder を有効化する必要が出てきたが、 GET_STARTED.md への記載がない
https://github.com/yumemi-inc/flutter-mobile-project-template/pull/250

### 提案の詳細

GET_STARTED.md に grinder の有効化手順を追加する

### 代替案

grinder をグローバルで有効化しなくても使えるのであれば、その方法で melos.yaml を修正してもいいかも

### 環境

```Markdown
- Commit Hash: 3c5359324a723097f7cc871ed7f24d2c2cd6ace3
```

**Comment by blendthink** [comment]
@tatsutakein 
こちらご確認の上、ご対応お願いできますでしょうか 🙏

**Comment by tatsutakein** [comment]
社内 Slack にて協議し、CLI としての grinder は利用しない方針で進める想定です 🙋
