### ISSUE TITLE
[Bug]: catalogのBuilderAddonの挙動が想定通りでない

### ISSUE THREAD

**Issue by K9i-0** [yumemi-inc/flutter-mobile-project-template#291]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 現在の動作

scaffoldFinder.hasFoundが常にfalseでScaffoldがある場合もScaffoldでラップされている
https://github.com/yumemi-inc/flutter-mobile-project-template/blob/main/apps/catalog/lib/main.dart#L57-L65

### 環境

```Markdown
- Commit Hash: 0153501e8487f388e99243d36f56509ea98f9def
- App Version: 1.0.0
- Platform: iOS 17.2.1, Android 14 API level 34
```

**Comment by blendthink** [comment]
@mj-hd 
作業時間確保できないかと思いますので、アサインから削除させていただきました 🙏

**Comment by nerd0geek1** [comment]
@K9i-0 @blendthink 
Widgetbookに詳しくないのですが、`find`を`flutter_test`からimportしているのは良いのでしょうか？

**Comment by K9i-0** [comment]
@nerd0geek1 
findがおそらくtest中でしか機能しなくて、このIssueのような問題に繋がってると思ってます 🙏

**Comment by nerd0geek1** [comment]
@K9i-0 
意図としては以下の通りで良いでしょうか？
- buildメソッドが以下のようにScaffoldを含む > Scaffoldでラップしない
  ```
  @override
    Widget build(BuildContext context, WidgetRef ref) {
      return Scaffold(
        body: Container(),
      );
    }
  ```
- buildメソッド内にScaffoldを含まない > Scaffoldでラップする

**Comment by Yamasaki-pan961** [comment]
@nerd0geek1 
> 意図としては以下の通りで良いでしょうか？
> buildメソッドが以下のようにScaffoldを含む > Scaffoldでラップしない
> buildメソッド内にScaffoldを含まない > Scaffoldでラップする

実装時はそのように考えてました！

そもそも「buildメソッド内にScaffoldを含まない > Scaffoldでラップする」こと自体不要な気がしてきました

**Comment by Yamasaki-pan961** [comment]
@nerd0geek1 
背景が真っ黒になるという理由でScaffoldつけるようにしたことを思い出しました。

以下のようにMaterialで囲むのはどうでしょうか？
Theme(light / dark)への追従もできそうです
```dart
        BuilderAddon(
          name: 'Material',
          builder: (context, child) {
            return Material(
              child: child,
            );
          },
        ),
```

<img width="1187" alt="image" src="https://github.com/user-attachments/assets/1a132bcc-38db-4e77-bf76-ab64027b3882">

**Comment by blendthink** [comment]
> @nerd0geek1 背景が真っ黒になるという理由でScaffoldつけるようにしたことを思い出しました。
> 
> 以下のようにMaterialで囲むのはどうでしょうか？ Theme(light / dark)への追従もできそうです

@Yamasaki-pan961 
Material で囲ってしまうと、タップ領域やエフェクトが変化してしまうケースがあるため、おすすめできません 🙏

**Comment by Yamasaki-pan961** [comment]
@blendthink 
ご意見ありがとうございます！

単純にColordBoxにするのがよさそうですかね？
```dart
BuilderAddon(
  name: 'BackgroundColor',
  builder: (context, child) {
    return ColoredBox(
      color: Theme.of(context).scaffoldBackgroundColor,
      child: child,
    );
  },
),
```

**Comment by nerd0geek1** [comment]
@Yamasaki-pan961 @blendthink 
そもそも論なんですが、条件分岐を行わずにScaffoldで囲ってしまう、ではだめですかね？
WidgetBookで表示しようと思う対象は画面というより、コンポーネントレベルかと思うので、
無条件にScaffoldで囲ってしまうでも困ることはないのではないかと。

**Comment by blendthink** [comment]
> @Yamasaki-pan961 @blendthink 
> 
> そもそも論なんですが、条件分岐を行わずにScaffoldで囲ってしまう、ではだめですかね？
> 
> WidgetBookで表示しようと思う対象は画面というより、コンポーネントレベルかと思うので、
> 
> 無条件にScaffoldで囲ってしまうでも困ることはないのではないかと。

@nerd0geek1 
案件によっては画面も対象なのです🙏

**Comment by nerd0geek1** [comment]
@blendthink 
なおほど。
それでいうと、SafeArea部分も見直したほうが良いですかね？
(現状、すべてのWidgetをSafeAreaで囲ってしまうことになるため、デザインによっては不都合が生じそう。)

**Comment by blendthink** [comment]
> @blendthink 
> 
> なおほど。
> 
> それでいうと、SafeArea部分も見直したほうが良いですかね？
> 
> (現状、すべてのWidgetをSafeAreaで囲ってしまうことになるため、デザインによっては不都合が生じそう。)

おそらくそうだと思います！
ただ、そこの問題は今のところ上がってないのでひとまずは Scaffold だけ対応でいいかなと思います👍
