### ISSUE TITLE
[Improve]: CIに循環依存の検知を含める

### ISSUE THREAD

**Issue by K9i-0** [yumemi-inc/flutter-mobile-project-template#292]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 背景

melos list -cyclesコマンドで循環依存があった時にCIで分かるようにしたい
https://melos.invertase.dev/commands/list#--cycles

### 環境

```Markdown
- Commit Hash: 0153501e8487f388e99243d36f56509ea98f9def
- App Version: 1.0.0
- Platform: iOS 17.2.1, Android 14 API level 34
```

**Comment by blendthink** [comment]
📝 
pubspec.lock ファイルが変更されたら、循環依存検知用のワークフローを check-pr.yaml から実行する

**Comment by blendthink** [comment]
@mj-hd 
作業時間確保できないかと思いますので、アサインから削除させていただきました 🙏
