### ISSUE TITLE
[Improve]: デバッグ画面への導線を shift + D に変更する

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#298]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 背景

現状はホーム画面の AppBar のボタンからしか遷移できず、使い勝手が悪い

### 提案の詳細

FlutterKaigi 2024 のように実装する

- デバッグ機能に独自ルートを作成
  - https://github.com/FlutterKaigi/2024/blob/main/packages/app/features/debug/lib/src/routing/router.dart
- debug 実行時にのみショートカットを定義する
  - https://github.com/FlutterKaigi/2024/blob/47ac4ae0fb95901771366cdd795b317154a1373c/apps/app/lib/main.dart#L69-L98

### 代替案

特になし

### 環境

```Markdown
- Commit Hash: 654675605c2876bbc5cd018a6ff5ba9a8663f12e
```

**Comment by tatsutakein** [comment]
やったことがなくておもしろそうなのでやってみます 🙋

**Comment by tatsutakein** [comment]
@blendthink 
これって、タイトルにあるとおり「変更」で良さそうでしょうか？ 👀

**Comment by blendthink** [comment]
> @blendthink 
> 
> これって、タイトルにあるとおり「変更」で良さそうでしょうか？ 👀
> 
> 

@tatsutakein 
はい！既存の遷移は削除でお願いします！

**Comment by tatsutakein** [comment]
> > @blendthink
> > これって、タイトルにあるとおり「変更」で良さそうでしょうか？ 👀
> 
> @tatsutakein はい！既存の遷移は削除でお願いします！

ご回答ありがとうございます！
合点承知です 💪
