### ISSUE TITLE
[Improve]: メンテナンス関連の実装を features/maintain パッケージに切り出す

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#304]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 背景

メンテナンスは機能として切り出すことが適切そう

### 提案の詳細

メンテナンス関連のものを features/maintain パッケージに切り出す

### 環境

```Markdown
- Commit Hash: d601817f0817390ce5402318f9f7cb4ae3ba7f94
```

**Comment by macneko-ayu** [comment]
やります！
