### ISSUE TITLE
[Improve]: 強制アップデート関連の実装を features/force_update パッケージに切り出す

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#305]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 背景

強制アップデートは機能として切り出すことが適切そう

### 提案の詳細

強制アップデート関連の実装を features/force_update パッケージに切り出す

### 環境

```Markdown
- Commit Hash: d601817f0817390ce5402318f9f7cb4ae3ba7f94
```

**Comment by tatsutakein** [comment]
やります 🙋
