### ISSUE TITLE
多言語対応をマルチパッケージ構成に対応する

### ISSUE THREAD

**Issue by iseruuuuu** [yumemi-inc/flutter-mobile-project-template#41]
### これに関する既存の Issue はありますか？

- [x] 既存の Issue はありませんでした

### 動機

[多言語対応#3](https://github.com/yumemi-inc/flutter-mobile-project-template/issues/3)の作業時に、現状（2024/01/05）だとマルチパッケージ構成になっていないため、[デザインシステムのパッケージ化#22](https://github.com/yumemi-inc/flutter-mobile-project-template/issues/22)がマージされた後に多言語対応をマルチパッケージ構成に対応する必要があるため、このIssuesを作成しました。

# 概要

- 多言語対応をマルチパッケージ構成に対応する

https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization
https://qiita.com/blendthink/items/ca9fddf2b977400c6259

### 提案

# 提案

**Comment by iseruuuuu** [comment]
https://github.com/yumemi-inc/flutter-mobile-project-template/issues/22がマージされた後に作業予定です🗒️

**Comment by blendthink** [comment]
apps/app/lib/feature/setting を packages/features/setting パッケージとして切り出して、この中の「テーマ設定」を多言語対応する

**Comment by iseruuuuu** [comment]
こちらのIssuesが完了した後に進める予定です。
https://github.com/yumemi-inc/flutter-mobile-project-template/issues/58

**Comment by iseruuuuu** [comment]
こちらのIssuesが完了した後に進める予定です
https://github.com/yumemi-inc/flutter-mobile-project-template/issues/81
