### ISSUE TITLE
UI カタログ

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#5]
- Widgetbook を利用する

**Comment by Kotaro666-dev** [comment]
## Widgetbook の利用方法のイメージ

- [Flutter 導入から5年。サイバーエージェントのクロスプラットフォーム開発の現在地](https://www.cyberagent.co.jp/way/list/detail/id=29474)

**Comment by Kotaro666-dev** [comment]
# TODO

JetBrains IDE の GUI でビルドする際に便利な run catalog の設定ファイルの導入をしてください。

## 背景

https://github.com/yumemi-inc/flutter-mobile-project-template/pull/49#issuecomment-1885966119

**Comment by Yamasaki-pan961** [comment]
@blendthink @Kotaro666-dev 
> ## Widgetbook の利用方法のイメージ
> * [Flutter 導入から5年。サイバーエージェントのクロスプラットフォーム開発の現在地](https://www.cyberagent.co.jp/way/list/detail/id=29474)

こちらの記事にある「Flutter WebをGitHub Pagesにデプロイしてレビューを容易にする」のは、一旦別タスクで良いですか？
分けた方が作業しやすいと思いました。

**Comment by blendthink** [comment]
@Yamasaki-pan961 
別タスクで OK です！

**Comment by Yamasaki-pan961** [comment]
issueさくせいしました！
- https://github.com/yumemi-inc/flutter-mobile-project-template/issues/79

**Comment by Yamasaki-pan961** [comment]
## 実装予定
- こちらを参考に有用なAddonを追加していく
  - https://docs.widgetbook.io/
- Telemetoryのオプトアウトを設定する
- フォルダ構成に関するREADMEを追加する
