### ISSUE TITLE
Navigation に go_router を使用する

### ISSUE THREAD

**Issue by morikann** [yumemi-inc/flutter-mobile-project-template#51]
Navigation パッケージとして以下を導入する。
- go_router
- go_router_builder

**Comment by Kotaro666-dev** [comment]
CC: @morikann 

# go_router 導入後に実施したいこと

本 issue #51 が完了後、 メンテナンスモード・強制バージョンアップ #24 の一部として以下の機能を実装していきたい。

## go_router の redirect 機能を使って、メンテナンスモードと強制バージョンアップ機能の画面を表示する基盤を用意する

> Redirection changes the location to a new one based on application state. For example, redirection can be used to display a sign-in screen if the user is not logged in.

トップレベルで `redirect` を定義することで、ルート位置に関係なくリダイレクトすることができそう。

> Top-level redirection: Defined on the GoRouter constructor. Called before any navigation event.

参考資料: https://pub.dev/documentation/go_router/latest/topics/Redirection-topic.html

以下はコード例。

```dart
redirect: (BuildContext context, GoRouterState state) {
  if (isMaintenanceMode) {
    return '/maintenanceModeScreen';
  } else if (isForceUpdate) {
    return '/forceUpdateDialog';
  }   
},
```

## 注意点

リダイレクト回数制限のプロパティが存在し、デフォルト値が 5 に設定されている。

> You can specify a redirectLimit to configure the maximum number of redirects that are expected to occur in your app. By default, this value is set to 5. GoRouter will display the error screen if this redirect limit is exceeded (See the [Error handling](https://pub.dev/documentation/go_router/topics/Error%20handling-topic.html) topic for more information on the error screen.)

https://github.com/flutter/packages/blob/d21f3b861e32a937a56f60b33e432d6a092f8de6/packages/go_router/lib/src/router.dart#L131

## go_router の画面遷移でダイアログを表示する

参考資料を見る感じ、`Page` を継承したクラスを使ってダイアログ表示を実装できそう。

## 参考資料

- [How Do I Show a Dialog in Flutter Using a go_router Route?](https://stackoverflow.com/questions/75690299/how-do-i-show-a-dialog-in-flutter-using-a-go-router-route)
- [Adding Modal Routes to your GoRouter](https://croxx5f.hashnode.dev/adding-modal-routes-to-your-gorouter)

**Comment by morikann** [comment]
@Kotaro666-dev 

> 本 issue https://github.com/yumemi-inc/flutter-mobile-project-template/issues/51 が完了後、 メンテナンスモード・強制バージョンアップ https://github.com/yumemi-inc/flutter-mobile-project-template/issues/24 の一部として以下の機能を @Kotaro666-dev が実装していきたい。

こちら承知しました！

@morikann がやることとしては go_router の導入 + 既存の画面遷移を go_router に置き換えることをやります。

メンテナンスモードの一部であるリダイレクトなどは @Kotaro666-dev さんにお願いできればと思います🙏
