### ISSUE TITLE
ARCHITECTURE.mdを更新する

### ISSUE THREAD

**Issue by Yamasaki-pan961** [yumemi-inc/flutter-mobile-project-template#53]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 動機

マルチパッケージ構成におけるパッケージの分割方法やディレクトリ構造について認識合わせをするためドキュメント化する必要がある。

### 提案

このプロジェクトは以下のプロジェクトを参考に依存関係を構築する。
https://github.com/android/nowinandroid
```
cores 内のパッケージは apps 内のアプリからも features 内のパッケージからも、cores 内のパッケージからも呼び出されるものです。
features 内のパッケージは apps 内のアプリからのみ呼び出されるものです。
責務については、どう切り出すかサービスによっても変わってくるところがあるので、都度相談する
```

**Comment by tatsutakein** [comment]
designsystem パッケージの追加をやったこともあるので、ついでにこちら対応しようと思います〜 🙋
