### ISSUE TITLE
[Feature]: masonでパッケージを追加する際、SDKバージョンを自動で反映させる

### ISSUE THREAD

**Issue by Yamasaki-pan961** [yumemi-inc/flutter-mobile-project-template#63]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 動機

masonでパッケージを追加する際、SDKバージョンはbrickテンプレートに記載されているバージョンで固定されてしまう。
プロジェクトのバージョンに合わせて自動でバージョンを設定して欲しい。

### 提案

brickにhooksを設定し、動的にテンプレートからコード生成を行えるようにする。

**Comment by Yamasaki-pan961** [comment]
`pubspeck.yaml`のSDKバージョンはテンプレート作成後に`melos bs`を実行するhooksを設定したので解決済み。

## Next
`yumemi_lints`のバージョン設定を解決する必要がある。

**Comment by morikann** [comment]
yumemi_lints で ↓ の実装が終わった後に本チケットを行う。📝 
[[Feature Request]: Update analysis_options.yaml using a command](https://github.com/yumemi-inc/flutter-yumemi-lints/issues/88)

### 実装イメージ
`mason make cores_package_flutter` の実行の際に hooks として ↑ のコマンドを実行する。（`melos bs` の後に）

**Comment by morikann** [comment]
yumemi_lints v2.0 がリリースされたら着手する 📝
