### ISSUE TITLE
[Refactor]: mason.yamlの最終行に改行を追加する 

### ISSUE THREAD

**Issue by Yamasaki-pan961** [yumemi-inc/flutter-mobile-project-template#69]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 動機

https://github.com/yumemi-inc/flutter-mobile-project-template/pull/62#discussion_r1456758873

### 提案

mason.yamlの最終行に改行を追加する

**Comment by Yamasaki-pan961** [comment]
@blendthink 
brickを追加するコマンド`mason add <brick-name>`を使用すると自動的に最終行が消えてしまうため、このissueは対応しない方向で行きます。

LGTMいただけますか！？

**Comment by blendthink** [comment]
@Yamasaki-pan961 
おっと、そうだったのですね、、！
お手数おかけしました 🙏 
それであれば仕方ないと思うので対応しない方針で LGTM です！！
