### ISSUE TITLE
[Improve]: パッケージ追加用のbrickを改善する

### ISSUE THREAD

**Issue by Yamasaki-pan961** [yumemi-inc/flutter-mobile-project-template#70]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 動機

https://github.com/yumemi-inc/flutter-mobile-project-template/pull/62#discussion_r1456843623

### 提案

flutter や dart の create コマンドを実行した後に mason のコマンドを実行して必要なもののみ上書きできるようにする。

**Comment by morikann** [comment]
`mason make` でパッケージを作成した後に hooks で `melos bs` を実行することで、pubspec.yaml のバージョンはプロジェクトに合わせて変更されるようになっています。

また、analysis_options.yaml に記載する lint バージョンをプロジェクトに変更させる対応につきましては ↓ で issue が作成されていますので、本 issue は close します。
https://github.com/yumemi-inc/flutter-mobile-project-template/issues/63
