### ISSUE TITLE
[Feature]: Pull Requestでアプリを確認できるようにする

### ISSUE THREAD

**Issue by Yamasaki-pan961** [yumemi-inc/flutter-mobile-project-template#79]
### これに関する既存の Issue はありますか？

- [x] 既存の Issue はありませんでした

### 動機

Pull Requestで動作確認できるようになるとレビュー効率が上がる
https://github.com/yumemi-inc/flutter-mobile-project-template/issues/5#issuecomment-1885965014

### 提案

以下を参考に、アプリやwidget_bookを確認できるGitHub Actionを組む
- [Flutter 導入から5年。サイバーエージェントのクロスプラットフォーム開発の現在地](https://www.cyberagent.co.jp/way/list/detail/id=29474)

**Comment by tatsutakein** [comment]
📝 デプロイするのは Widgetbook のみで、アプリ側は対象としない
