### ISSUE TITLE
[Feature]: features/app/setting/provider/ThemeModeNotifierのパッケージへの切り出し 

### ISSUE THREAD

**Issue by iseruuuuu** [yumemi-inc/flutter-mobile-project-template#81]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 動機

- [多言語対応をマルチパッケージ構成に対応する](https://github.com/yumemi-inc/flutter-mobile-project-template/issues/41)に取り組んだ際に、`apps/app/lib/feature/setting` を `packages/features/setting`パッケージとして切り出して、`setting_page`内のWidgetのAppBarに多言語対応しようと思っていました。
- しかし、`apps/app/lib/feature/setting`の中には、[`theme_mode_notifier.dart`](https://github.com/yumemi-inc/flutter-mobile-project-template/blob/main/apps/app/lib/feature/setting/provider/theme_mode_notifier.dart)があり、複数のパッケージから themeModeNotifierProvider が参照されてしまい、依存させたくないパッケージ同士が依存してしまう問題があると考えています。
- packages/features/setting はゆくゆくはPackages化した方が良さそうという認識があるため、`themeModeNotifierProvider`もパッケージの切り出しが必要だと考えています。

### 提案

- `themeModeNotifierProvider`を`cores/data` に切り出す。

### 注意点

-  theme_mode_notifier.dart に記載された以下のコメント対応を行う。

```
/* TODO: Remove cores_data dependency from app package when this class is
     extracted into feature package
 */
```

**Comment by Kotaro666-dev** [comment]
@iseruuuuu 

本 issue 対応時に、 `theme_mode_notifier.dart` に記載された以下のコメント対応も一緒にお願いします！ 🙏 

```
/* TODO: Remove cores_data dependency from app package when this class is
     extracted into feature package
 */
```

## 背景

https://github.com/yumemi-inc/flutter-mobile-project-template/pull/65#discussion_r1455063065

**Comment by iseruuuuu** [comment]
@Kotaro666-dev 
教えていただきありがとうございます！issuesの方に記載してみました🙇
