### ISSUE TITLE
GitHub Actions で UI カタログの GitHub Pages へデプロイ

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#9]

**Comment by Yamasaki-pan961** [comment]
確認漏れで同じようなissueを作ってしまいました。
- https://github.com/yumemi-inc/flutter-mobile-project-template/issues/79

本issueを削除しても良いでしょうか？

**Comment by blendthink** [comment]
@Yamasaki-pan961 
はい！
こちらの Issue クローズしていただいて大丈夫です！
（というかこちらでクローズしておきます、、！）
