### ISSUE TITLE
テンプレート機能利用時に VS Code での GitHub Copilot を無効化するワークフローの作成

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#97]
#96 を先に対応する

## 対応すること

- [flutter-training-template のワークフロー](https://github.com/yumemi-inc/flutter-training-template/blob/main/.github/workflows/template-cleanup.yaml) のようにテンプレート機能利用時に VS Code での GitHub Copilot を無効にするワークフローを作成する
  - jsonc をパースして copyWith して上書きするようなツールがあれば使ってもいいかも
  - いったん、力技でも動けば OK

**Comment by Yamasaki-pan961** [comment]
### 技術調査
通常のjsonファイルであれば [`jq`](https://github.com/jqlang/jq) というツールを使えば値の上書き処理は可能

しかし`jq`はjsonc(json witch comment)ファイルに対応していないため、処理や運用方法を考える必要がある
https://github.com/jqlang/jq/wiki/FAQ#processing-not-quite-valid-json

上記はnpmパッケージの[`json`](https://www.npmjs.com/package/json)でも同様であった。

## 運用案
個人的には2が良いかなと思います。

### 1. jsoncをcopyWithできるツールを開発する
元ファイルのコメントを引き継ぐようなcopyWithツールを実装する。
問題点は、個人的に実装が難しそうだと感じた。


### 2. テンプレート機能利用時にコメントを引き継がない

テンプレート機能利用時に`settings.json`のコメントを引き継がないこととすれば、処理が容易になる。
jsoncをjsonに変換し、`jq`を使って値の上書きを行う

問題点は、コメントが引き継がれないこと

### 3. jsoncを使わない
`settings.json`を通常のjsonファイルとして扱うようにすることで、`jq`を使えるようにする。

問題点は
- コメントが書けないこと
- 完璧なjsonファイルを用意する必要があること
例えば以下のようにKey / Valueの最終行に`,`が含まれると入力値エラーとなる。
そして、vscodeのフォーマッタではこの`,`を削除してくれない。
```json
{
  "github.copilot.editor.enableCodeActions": true,
  "github.copilot.editor.enableAutoCompletions": true,
}
```
