### ISSUE TITLE
[Bug]: mason で生成される cores 配下のパッケージ名やファイル名に統一性がない

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#99]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 現在の動作

- 既存のパッケージ名と統一性がない
  - pubspec.yaml の `name` が `core_{{package_name.snakeCase()}}` になっている
- brick 名が core_package_flutter, core_package_dart
- core_package_flutter と core_package_dart のプロジェクト構成に統一性がない
  - core_package_flutter には src ディレクトリがない
  - core_package_flutter にはファイル名に core_ がついている

### 期待される動作

- 既存のパッケージ名と統一する
  - pubspec.yaml の `name` を `cores_{{package_name.snakeCase()}}` にする
  - 各ファイルの import 文を修正する
- brick 名を cores_package_flutter, cores_package_dart に変更する
- core_package_flutter のプロジェクト構成を core_package_dart に合わせる

### 環境

```Markdown
- Commit Hash: 9cabccfeb867a4eaa54d6110a30114115b41dd9e
```

**Comment by iseruuuuu** [comment]
![imo](https://img.shields.io/badge/review-imo-orange.svg)
`LICENSE`や`CHANGELOG.md`が追加されているように見えますが、必要がない場合は削除した方いいのではないかと思いました🧐
